//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mikszath_Madach_Kviz_2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mikszath_Madach_Kviz_2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Actions_help_hint_icon_stretched {
            get {
                object obj = ResourceManager.GetObject("Actions_help_hint_icon_stretched", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Evaluate_try_stretched {
            get {
                object obj = ResourceManager.GetObject("Evaluate_try_stretched", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A táblázatot tervezte és kivitelezte:
        ///Bőhm András
        ///
        ///A szoftvert írta:
        ///Donkó István
        ///
        ///Az XYZ megbízásából.
        /// </summary>
        public static string footerString {
            get {
                return ResourceManager.GetString("footerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap help_icon_stretched {
            get {
                object obj = ResourceManager.GetObject("help_icon_stretched", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segítség.
        /// </summary>
        public static string helpFormTitle {
            get {
                return ResourceManager.GetString("helpFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Útmutató.
        /// </summary>
        public static string helpString {
            get {
                return ResourceManager.GetString("helpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Súgások: .
        /// </summary>
        public static string hintCountString {
            get {
                return ResourceManager.GetString("hintCountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Súgás.
        /// </summary>
        public static string hintString {
            get {
                return ResourceManager.GetString("hintString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refresh_stretched {
            get {
                object obj = ResourceManager.GetObject("refresh_stretched", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Újrakezdés.
        /// </summary>
        public static string shuffleString {
            get {
                return ResourceManager.GetString("shuffleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próbálkozások: .
        /// </summary>
        public static string submitCountString {
            get {
                return ResourceManager.GetString("submitCountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiértékelés.
        /// </summary>
        public static string submitString {
            get {
                return ResourceManager.GetString("submitString", resourceCulture);
            }
        }
    }
}
